### ISSUE TITLE
[Bug] Minecraft freezing every now and then

### ISSUE THREAD

**Issue by physanus** [NotEnoughUpdates/NotEnoughUpdates#159]
**Mod Version**
NotEnoughUpdates-2.1-FirstDangerousReleaseOf2022

**Describe the bug**
Minecraft freezes, that's pretty much it. I do not get any specific error message and there's also not really much to find in the logs. 
The launcher shows `Process crashed with exit code -805306369` (after I force-closed Minecraft) and the last error is from a couple of seconds before the freeze (`NullPointerException` in `net.minecraft.util.Util.func_181617_a`, you can see that in the video).
It randomly happens both after a fresh restart (like during the first few minutes) and after severeal hours when the game seemed to run just fine.
There also does not seem to be any correlation to any actions I do, except for always freezing on Hypixel. However, I use Forge/1.8 pretty much only for Hypixel, so maybe my assumption is wrong and it could also freeze on other servers. In the specific video, the client froze a couple moments after I got disconnected from Hypixel due to `java.io.IOException: An existing connection was forcibly closed by the remote host`. I do not remember whether that always precedes the freeze; that could and I assume it is probably just a random disconnect. As well as switching the world right beforehand.

I used `NotEnoughUpdates-2.1-FirstDangerousReleaseOf2022` for this test & video (I also removed all other mods like Skyblock Addons). Typically it freezes every ~2-3 days, sometimes also several times per day. Minecraft does not freeze with the current configuration when I remove the NEU mod from the plugins folder. I also tested a formerly latest commit from the master branch, which froze, too. Currently I have the now-latest commit [ec8ec6b](https://github.com/NotEnoughUpdates/NotEnoughUpdates/commit/ec8ec6bb6a6b82cd4369e61d0e3cd4539b9c8295) loaded, I'll post an update once it freezes.

Maybe there is a way to debug the freeze? I am able to use an IDE and set breakpoints if that is necessary. Feel free to tell me what to do so you can narrow down the issue. 

MC startup args: `-Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`

**To Reproduce**
n/a

**Expected behavior**
No freeze

**Attachments**

(YouTube Video, click the image)
[![YouTube](https://img.youtube.com/vi/4E1yO5FzPsk/0.jpg)](https://youtu.be/4E1yO5FzPsk?t=113)

**Comment by physanus** [comment]
It just froze with the lastest commit [ec8ec6b](https://github.com/NotEnoughUpdates/NotEnoughUpdates/commit/ec8ec6bb6a6b82cd4369e61d0e3cd4539b9c8295).

**Comment by xExoticc** [comment]
Mine does the same thing. No certain times or intervals just happens randomly, maybe 2-3 times a day more or less. I don't have a video or a screenshot to show but it doesn't happen after neu is removed from mod folder. If it unfreezes a few moments after freezing I will be placed in limbo if not and I click a few times it opens the "this window is not responding" with the options to wait for it to respond or to close minecraft.

**Comment by NopoTheGamer** [comment]
> Mine does the same thing. No certain times or intervals just happens randomly, maybe 2-3 times a day more or less. I don't have a video or a screenshot to show but it doesn't happen after neu is removed from mod folder. If it unfreezes a few moments after freezing I will be placed in limbo if not and I click a few times it opens the "this window is not responding" with the options to wait for it to respond or to close minecraft.

Are you using neu2.1-Watching-3?

**Comment by QuarkField** [comment]
hate to necro post but I experience the same behavior. sometimes it'll only be frozen for 10 seconds and I'll spawn in limbo. very annoying because I gemstone mine, and once my lobby is set up I don't leave it for multiple hours.

**Comment by romangraef** [comment]
ive found that this is relating to neuah a while ago (at least according to jstack). ive also made a fix, but due to the extremely unpredictable nature of this bug im not sure if the fix is working. the fix should be present in the latest prerelease (watching-4, and already a few versions before that). we also do not use the github issue tracker, so ill be closing this PR; if this is happening again on a new/fixed version, please post about it in our discord
