### ISSUE TITLE
[Feature Request] Add `The Matriarch` / `Heavy Pearls` to the todo overlay

### ISSUE THREAD

**Issue by MrGcGamer** [NotEnoughUpdates/NotEnoughUpdates#208]
Add `The Matriarch` / `Heavy Pearls` to the todo overlay

**Comment by jani270** [comment]
https://github.com/NotEnoughUpdates/NotEnoughUpdates/commit/79bc28639e966415a97b1f21dd11617c6a4e0215 🙂
