### ISSUE TITLE
[Bug] Fps drops

### ISSUE THREAD

**Issue by BluePotatoBP** [NotEnoughUpdates/NotEnoughUpdates#245]
**Mod Version: 2.1-Watching-3** 

**Describe the bug**
After playing for ~20min if I left click the game drops down to 30fps or worse, this also persists if I hold down left click and is even more noticeable when I pan the camera. 

I should note that it seems like a memory leak but what do I know, allocated ram is at 100% when this is happening. 
I'm running the game on 4gb of ram with 16gb in my system. All mods I use are up to date and I tried removing them one by one to see which ones causing this and it came down to NEU. This also didn't used to happen prior to NEU 2.0.

**To Reproduce**
1. Play for around 20 minutes
2. Left click

**Expected behavior**
The game not lagging when I press the left mouse button.

**Attachments**
Mod folder:
![image](https://user-images.githubusercontent.com/52742857/185985607-730c991f-f9cc-4e0e-9a3c-cf330a968ab7.png)
Video showing the issue:
 https://youtu.be/2f5DGbje8d8

**Comment by BluePotatoBP** [comment]
Thanks for the rapid response, lovely working with you!

**Comment by NopoTheGamer** [comment]
Thanks for your reading ability, lovely working with you!
![image](https://user-images.githubusercontent.com/40329022/188264613-3c9fb8c4-beb3-4e96-b40f-780d3b5d17a2.png)

**Comment by BluePotatoBP** [comment]
Thanks for being a dick, eat shit! When someone has issues with your open source project, they come to your repo and submit a bug report, I've made a support thread in the discord, nobody could help and I was told to wait. I waited and no one showed up. I literally said "I'm going to open an issue over there just in case". Also you could have responded earlier with that same exact image and not wasted anyone's time.

**Comment by Lulonaut** [comment]
ok
