### ISSUE TITLE
[Bug] NEU profile viewer in dropper?

### ISSUE THREAD

**Issue by s3hMC** [NotEnoughUpdates/NotEnoughUpdates#250]
**Mod Version:** 
NotEnoughUpdates-2.1-FirstDangerousReleaseOf2022

**Describe the bug**
The ocean map's tooltip in the prototype dropper minigame is changed to the NEU profile viewer's. Clicking it works fine, though.

**To Reproduce**
1. Play dropper
2. In the map selector hover over the bottom right block on the first page

![image](https://user-images.githubusercontent.com/54605711/187508503-b9670c99-1da9-4bb6-b6db-9d964e7ffdcc.png)

**Comment by Lulonaut** [comment]
Please use the latest version, you can find it in the discord server.
