### ISSUE TITLE
[Bug] /locraw objects will be parsed if in any chat message

### ISSUE THREAD

**Issue by realmsclove** [NotEnoughUpdates/NotEnoughUpdates#35]
**Mod Version:** 
2.0.0

**Describe the bug**
Receiving any chat message with a /locraw string in it will make the mod think that was the result of a /locraw. This allows you to change other people's locations with a chat message and disable or enable mode-specific features such as the mining overlay and dungeon overlay. You can also delete the Skytils crystal hollows map and waypoints because it uses the same class as NEU but I don't see a way to file bug reports for that mod.

This happens because of [SBInfo::onChatMessage](https://github.com/NotEnoughUpdates/NotEnoughUpdates/blob/master/src/main/java/io/github/moulberry/notenoughupdates/util/SBInfo.java#L99) not properly validating locraw objects.

**To Reproduce**
1. Send a chat message matching the result of /locraw with the `mode` set to something other than its actual value (ie `{"mode":"dungeon","gametype":"","server":"","map":""}` if you're in the Crystal Hollows
2. Mode-specific features will be enabled/disabled

**Expected behavior**
The mod should only parse /locraw strings that are the result of running the command.

**Comment by MolEliza23** [comment]
https://user-images.githubusercontent.com/96449296/146841148-9d542855-158c-4e48-8884-69ef7135e1c9.MP4

**Comment by My-Name-Is-Jeff** [comment]
We do a considerable amount of trolling
