### ISSUE TITLE
EquipmentOverlay: NullPointerException

### ISSUE THREAD

**Issue by jani270** [NotEnoughUpdates/NotEnoughUpdates#471]
crashlog: https://hst.sh/raw/ayuwucager

**Comment by romangraef** [comment]
thats inside an exception handler?? https://github.com/NotEnoughUpdates/NotEnoughUpdates/blob/8874ae66e226a6bf59a0431117f34d2a47c1719c/src/main/java/io/github/moulberry/notenoughupdates/util/ItemUtils.java#L261-L263

**Comment by jani270** [comment]
> thats inside an exception handler??
> 
> https://github.com/NotEnoughUpdates/NotEnoughUpdates/blob/8874ae66e226a6bf59a0431117f34d2a47c1719c/src/main/java/io/github/moulberry/notenoughupdates/util/ItemUtils.java#L261-L263

They are using NEU 2.1, maybe smth got changed in the Util so the lines moved?

**Comment by romangraef** [comment]
![image](https://user-images.githubusercontent.com/20768569/205322210-78f5b33e-a244-460f-b8b8-9c7cb3a6b259.png)
I love no release on neu/neu

**Comment by jani270** [comment]
> ![image](https://user-images.githubusercontent.com/20768569/205322210-78f5b33e-a244-460f-b8b8-9c7cb3a6b259.png) I love no release on neu/neu

Ive asked them to use prerelease, maybe its fixed or maybe we get a better crashlog

**Comment by romangraef** [comment]
```
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:NotEnoughUpdates/NotEnoughUpdates.git
 * [new tag]           v2.1.0 -> v2.1.0
 ```

**Comment by romangraef** [comment]
Ig this makes more sense: 

https://github.com/NotEnoughUpdates/NotEnoughUpdates/blob/v2.1.0/src/main/java/io/github/moulberry/notenoughupdates/util/ItemUtils.java#L262-L264

**Comment by romangraef** [comment]
ig this is the rare case of: their repo has the actual pet as an item, but does not have the pet item as an item

**Comment by NopoTheGamer** [comment]
Did this get fixed?

**Comment by jani270** [comment]
> Did this get fixed?

Dont think so

**Comment by jani270** [comment]
This issue is still not fixed with alpha 8: https://hst.sh/raw/zateguhege
