### ISSUE TITLE
MinionHelper: Shows price for custom skyblock item

### ISSUE THREAD

**Issue by jani270** [NotEnoughUpdates/NotEnoughUpdates#472]
In the newest skyblock update they added something like pelts called "North Stars", ive added a custom item (same as gold medals) to the repo see [here](https://github.com/jani270/NotEnoughUpdates-REPO/blob/booksss/items/SKYBLOCK_NORTH_STAR.json).
Unfortunately the minion helper shows a price (1 coin per) for the custom item see: 
![image](https://user-images.githubusercontent.com/69345714/205324099-e5f7f120-d8b3-4276-9438-23f797069840.png)

**Comment by heyngra** [comment]
North Stars are not in the API
Pelts are in the API,

Should we get amount of North Stars just from fetching it while being on Jerry Island or do you have any other idea?

**Comment by jani270** [comment]
> North Stars are not in the API Pelts are in the API,
> 
> Should we get amount of North Stars just from fetching it while being on Jerry Island or do you have any other idea?

Well the issue isnt about them not showing how many you have, the issue is about the custom item showing 300 coins (1per) as a price which shouldnt happen.
