### ISSUE TITLE
PetLeveling: NullPointerException

### ISSUE THREAD

**Issue by jani270** [NotEnoughUpdates/NotEnoughUpdates#486]
https://hst.sh/raw/rusepagulo

**Comment by heyngra** [comment]
can this still occur? not sure if it's not fixed in #447, and the crash log is from the version without this PR
![image](https://user-images.githubusercontent.com/25665974/206927963-8a2e178a-1ecb-47c9-afff-bd07dc6316bb.png)

**Comment by jani270** [comment]
> can this still occur? not sure if it's not fixed in #447, and the crash log is from the version without this PR ![image](https://user-images.githubusercontent.com/25665974/206927963-8a2e178a-1ecb-47c9-afff-bd07dc6316bb.png)

Yes edited
