### ISSUE TITLE
[Bug] pet moment

### ISSUE THREAD

**Issue by My-Name-Is-Jeff** [NotEnoughUpdates/NotEnoughUpdates#52]
**Mod Version:** which ever one is in neu i think 2.1.0

**Describe the bug** literally screenshot

**To Reproduce**
1.  get a pet
2.  open inventory

**Expected behavior**
get better lol

**Attachments**
https://cdn.discordapp.com/attachments/881403326938353684/927751053477285958/unknown.png

**Comment by Wyvest** [comment]
Click to open in NEU profile viewer
