### ISSUE TITLE
wardrob.

### ISSUE THREAD

**Issue by My-Name-Is-Jeff** [NotEnoughUpdates/NotEnoughUpdates#53]
https://github.com/NotEnoughUpdates/NotEnoughUpdates/blob/d6adec7cc55640af48f10517318f73f7a9d8b579/src/main/java/io/github/moulberry/notenoughupdates/NEUOverlay.java#L1832

**Comment by Lulonaut** [comment]
wardrob https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/blob/8e27908d2530b09107c2dedc48dc3c093c9dd45d/constants/disable.json#L5
