### ISSUE TITLE
MinionHelper: Cannot get minion for display name

### ISSUE THREAD

**Issue by jani270** [NotEnoughUpdates/NotEnoughUpdates#544]
https://hst.sh/nukajahegi.lua

Message from buying a flower minion in the dark auction: 
`[20:00:30] [Client thread/INFO]: [CHAT] §r§aYou crafted a §eTier I §9Flower Minion§a! That's a new one!
 §aCraft 20 more unique Minions to unlock your 30th Minion slot!§r` 
 
(Also the error message has no color code at the start very bad)

**Comment by VixidDev** [comment]
Believe this was solved with #573
