### ISSUE TITLE
Calendar Overlay: Empty Slots on the bottom right side and broken buttons

### ISSUE THREAD

**Issue by jani270** [NotEnoughUpdates/NotEnoughUpdates#585]
Hypixel removed a row in the calendar which causes this:
![image](https://user-images.githubusercontent.com/69345714/216587083-c53093e3-82a5-428c-8bf7-8b7ba0e9c30f.png)

**Comment by NopoTheGamer** [comment]
also breaks every button in neucalendar YEP

**Comment by jani270** [comment]
YEP
