### ISSUE TITLE
/neustats doesn't check for length

### ISSUE THREAD

**Issue by Madeleaan** [NotEnoughUpdates/NotEnoughUpdates#876]
In cases like [here](https://pastebin.com/5NmzavCM), the markdown is too large and a non-nitro users can't send it

**Comment by RayDeeUx** [comment]
isnt there the "upload as file" option or does that convert everything to txt and then the user has to specify its .md

**Comment by RayDeeUx** [comment]
also for clarification it's `/neustats full`

**Comment by RayDeeUx** [comment]
turns out it's been fixed here: https://github.com/NotEnoughUpdates/NotEnoughUpdates/commit/32e7f4704fe2639314451e39c32741a1900907c0
