### ISSUE TITLE
Storage overlay doesnt work if the first time you open it is with /ec

### ISSUE THREAD

**Issue by NopoTheGamer** [NotEnoughUpdates/NotEnoughUpdates#883]
![image](https://github.com/NotEnoughUpdates/NotEnoughUpdates/assets/40329022/f904ca9b-d357-47cc-ad87-8dc82fe0a089)

**Comment by Jumpy85Plays** [comment]
Same problem over here

**Comment by jani270** [comment]
> Same problem over here

That is incorrect, your problem comes from something else.

**Comment by Jumpy85Plays** [comment]
Is there anything i can do to fix this?? Ive been using the default non QoL modded storage interface as it either shows this for me or a "is locked" whenever i try to open the storage

**Comment by NopoTheGamer** [comment]
> Is there anything i can do to fix this?? Ive been using the default non QoL modded storage interface as it either shows this for me or a "is locked" whenever i try to open the storage

no

**Comment by nea89o** [comment]
For the time being: create a second profile.

Also don't use development channels for asking questions entirely unrelated to this PR.
