### ISSUE TITLE
neu dungeons map not showing my player 

### ISSUE THREAD

**Issue by yggysusugysvugugsv** [NotEnoughUpdates/NotEnoughUpdates#92]
![image](https://user-images.githubusercontent.com/68038124/157560904-ddeb7fcb-e71c-4c8b-b650-1abe24cab4a0.png)
![image](https://user-images.githubusercontent.com/68038124/157560913-dafd4559-56c0-4aa9-9a69-48a792c1f11f.png)

**Comment by LiamDun** [comment]
:chatting: why doesnt the dungeon map work someone pls help!!!!! :clueless: surely im the only one with this issue

**Comment by UnderscoreRayless** [comment]
:chatting: why doesnt the dungeon map work someone pls help!!!!! :clueless: surely im the only one with this issue

**Comment by yggysusugysvugugsv** [comment]
ok it is in the projects thing
